### ISSUE TITLE
DiagrammeR::mermaid plot cause text to fade away

### ISSUE THREAD

**Issue by Aeilert** [tonyfujs/Povcalnet_internal_guidelines#1]
For some reason the mermaid figure used in `Collaboration_in_Git.Rmd` cause the text to fade away.  

![image](https://user-images.githubusercontent.com/8194990/78003819-3fc40e00-7307-11ea-835c-9b5c68a40a4a.png)

Initial testing shows that the problem also occurs in other stand-alone R Markdown files, so it might be a bug related to the `DiagrammeR` package. The  temporary fix is to remove or comment out the relevant code chunk (see below).  

```{r,echo=FALSE} 
  DiagrammeR::mermaid(" 
  graph TD 
  A[Check out master branch]-->B[update master by pulling] 
  B-->C2[Solve conflicts] 
  B-->|if no conflicts|C[create your own branch] 
  C2-->C 
  C-->D[commit as many times you want] 
  D-->E[Push YOUR branch to remote for backup] 
  D-->A 
  ") 
```

**Comment by Aeilert** [comment]
Did some more searching. The problem is that the `mermaid.css` created by `DiagrammeR::mermaid()` overrides the general CSS for R Markdown. This has however been fixed in the latest development version of `DiagrammeR`, so we could consider upgrading to that or just wait until it is published on CRAN.  

If we want to upgrade to the latest Github-version we could add something like the following to `_common.R`. (Note: You might need to update some other packages before running the command. I for exampled needed to reinstall `glue` and `Rcpp`). 
```
if(packageDescription("DiagrammeR")$Version != "1.0.5.9000"){
  devtools::install_github("rich-iannone/DiagrammeR")
}
```

 As a reference see the the following discussions: 

https://github.com/rstudio/rmarkdown/issues/1768
https://github.com/rich-iannone/DiagrammeR/issues/375

**Comment by randrescastaneda** [comment]
Solved by updated packages and created a separate .mmd file.
